### ISSUE TITLE
The option to execute only notebooks seems to be broken with pytest 4.4.0

### ISSUE THREAD

**Issue by ocefpaf** [computationalmodelling/nbval#114]
Something changed in the latest pytest and the option `-p no:python` now returns `ValueError: unknown configuration value: 'python_files'`.
Downgrading `pytest` or not using the option fixes the problem.

Full traceback below.

```
Traceback (most recent call last):
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 927, in getini
    return self._inicache[name]
KeyError: 'python_files'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 934, in _getini
    description, type, default = self._parser._inidict[name]
KeyError: 'python_files'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/filipe/miniconda3/envs/FOLIUM/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 201, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 679, in pytest_cmdline_parse
    self.parse(args)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 896, in parse
    self._preparse(args, addopts=addopts)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 836, in _preparse
    self._consider_importhook(args)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 772, in _consider_importhook
    hook = _pytest.assertion.install_importhook(self)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 81, in install_importhook
    config._assertstate.hook = hook = rewrite.AssertionRewritingHook(config)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 63, in __init__
    self.fnpats = config.getini("python_files")
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 929, in getini
    self._inicache[name] = val = self._getini(name)
  File "/home/filipe/miniconda3/envs/FOLIUM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 936, in _getini
    raise ValueError("unknown configuration value: %r" % (name,))
ValueError: unknown configuration value: 'python_files'
```

**Comment by vidartf** [comment]
I think this is more suited as an issue on the pytest repo, along the lines of "Allow unknown config values in config files" (I would argue it somewhat makes sense to not allow unkown values on the CLI). An alternative would be for the pytest config file to allow for different headings for configuring plugins.

**Comment by vidartf** [comment]
PS: The change seems to have been brought about by pytest no longer loading plugins that have been disabled (the "python" plugin here).

**Comment by vidartf** [comment]
Is this still an issue? It seems to work with the latest py.test for me now.

**Comment by ocefpaf** [comment]
> Is this still an issue? It seems to work with the latest py.test for me now.

Sorry. Lost track of this. Let's close and I'll ping back once I can test with newer pytest versions.
